### Word Enbedding using Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am good developer',
    'understand the meaning of words',
    'the videos is good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good developer',
 'understand the meaning of words',
 'the videos is good']

In [4]:
# define vocabulary size
voc_size=10000

In [5]:
## OHE Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1455, 3424, 5768, 7236],
 [1455, 3424, 5768, 863],
 [1455, 4680, 5768, 9543],
 [2315, 3324, 8914, 3593],
 [1721, 1455, 8882, 5768, 6260],
 [1455, 7000, 8367, 8914]]

In [8]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
'''
2️⃣ Padding Sequences
What it does
This function makes all sequences the same length.
Neural networks require inputs with equal size.
Example sequences:
[1, 4, 6]
[2, 3]
[5, 7, 8, 9]
After padding:
[1, 4, 6, 0]
[2, 3, 0, 0]
[5, 7, 8, 9
'''
from tensorflow.keras.models import Sequential
'''
3️⃣ Sequential Model
from tensorflow.keras.models import Sequential
What it does

This creates a Sequential Neural Network model.

Sequential means layers are added one after another.

Structure:

Input → Layer1 → Layer2 → Layer3 → Output
'''


'\n3️⃣ Sequential Model\nfrom tensorflow.keras.models import Sequential\nWhat it does\n\nThis creates a Sequential Neural Network model.\n\nSequential means layers are added one after another.\n\nStructure:\n\nInput → Layer1 → Layer2 → Layer3 → Output\n'

In [16]:
# applying padding in ohe words to convert it in equal words 
sent_lenght=8
emd_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght) # i am applying pre means i want to de pre padding you can also apply post.

In [18]:
emd_docs

array([[   0,    0,    0,    0, 1455, 3424, 5768, 7236],
       [   0,    0,    0,    0, 1455, 3424, 5768,  863],
       [   0,    0,    0,    0, 1455, 4680, 5768, 9543],
       [   0,    0,    0,    0, 2315, 3324, 8914, 3593],
       [   0,    0,    0, 1721, 1455, 8882, 5768, 6260],
       [   0,    0,    0,    0, 1455, 7000, 8367, 8914]], dtype=int32)

In [13]:
## feature repreestation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_lenght))
model.compile('adam','mse')
'''In TensorFlow / Keras, compile() means preparing the model for training.
It tells the model:

Which optimizer to use → how weights will be updated

Which loss function to use → how error will be calculated

Which metrics to track (optional)'''

/opt/anaconda3/envs/annstream/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


'In TensorFlow / Keras, compile() means preparing the model for training.\nIt tells the model:\n\nWhich optimizer to use → how weights will be updated\n\nWhich loss function to use → how error will be calculated\n\nWhich metrics to track (optional)'

In [20]:
model.predict(emd_docs)

2026-03-13 18:21:37.043791: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 486ms/step


array([[[-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [ 0.00856643, -0.02159348,  0.04678768, -0.00585721,
          0.01842458,  0.03013641,  0.03287247, -0.02556921,
          0.04097632,  0.01471014],
        [-0.04467819, -0.02268804,  0.02630949, -0.01110391,
         -0.010229  , -0.01230748, -0.03225266,  0.01794882,
         -0.02929752,  0.04071635],
        [-0.01854879,  0.02440223,  0.01444764, -0.0

In [21]:
emd_docs[0]

array([   0,    0,    0,    0, 1455, 3424, 5768, 7236], dtype=int32)

In [24]:
model.predict(emd_docs[0].reshape(1,8))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


array([[[-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [ 0.00856643, -0.02159348,  0.04678768, -0.00585721,
          0.01842458,  0.03013641,  0.03287247, -0.02556921,
          0.04097632,  0.01471014],
        [-0.04467819, -0.02268804,  0.02630949, -0.01110391,
         -0.010229  , -0.01230748, -0.03225266,  0.01794882,
         -0.02929752,  0.04071635],
        [-0.01854879,  0.02440223,  0.01444764, -0.0

In [25]:
model.predict(emd_docs[1].reshape(1,8))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[[-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [-0.02843874, -0.02933792, -0.00228679,  0.03580649,
         -0.00269945,  0.02113828, -0.00013   ,  0.01402296,
          0.03382644, -0.02845477],
        [ 0.00856643, -0.02159348,  0.04678768, -0.00585721,
          0.01842458,  0.03013641,  0.03287247, -0.02556921,
          0.04097632,  0.01471014],
        [-0.04467819, -0.02268804,  0.02630949, -0.01110391,
         -0.010229  , -0.01230748, -0.03225266,  0.01794882,
         -0.02929752,  0.04071635],
        [-0.01854879,  0.02440223,  0.01444764, -0.0